version: 2.1

jobs:
  print_hello:
    docker:
      - image: alpine:latest
    steps:
     - run: echo hello
  print_world2:
    docker:
      - image: alpine:latest
    steps:
     - run: echo world

workflows:
  welcome:
   jobs:
    - print_hello
    - print_world2
